# ABOUTME: Student-facing Pydantic models for the moulinette evaluation contract.
# ABOUTME: This file is copied verbatim from moulinette/models_public.py — do not edit its shape.
#
# ============================================================================
# 【日本語解説】このファイルの立ち位置
# ============================================================================
# ここに定義されている5つの Pydantic モデルは、自作の型ではなく「採点システム
# (moulinette) 側のスキーマのコピー」である。フィールドを1つでも変えると採点が
# 壊れるため、上の ABOUTME コメントが明言する通り「形は編集禁止」。
#
# 役割は3種類に大別できる:
#   1. 入力契約  : moulinette → エージェント （MBPPTaskInput / SWEBenchTaskInput）
#   2. 内部設定  : エージェント内部だけで完結 （SandboxConfig）
#   3. 出力契約  : エージェント → moulinette （StepMetrics / SolutionOutput）
# ============================================================================
from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class StepMetrics(BaseModel):
    """Metrics for a single agent step.

    Each step corresponds to one LLM generate -> sandbox execute cycle.
    All fields are required for evaluation - empty strings are acceptable
    for steps where a field doesn't apply (e.g., no sandbox execution).
    """
    # -------------------------------------------------------------------
    # 【日本語解説】StepMetrics = 「Thought→Code→Observation」1周分の記録
    # -------------------------------------------------------------------
    # orchestrator.py の Orchestrator.run() が、ループを1周まわすたびに
    # このモデルのインスタンスを1個組み立てて steps リストに積んでいく。
    # 「本当に何が起きたか」を後から検証できるようにするための証跡。
    # -------------------------------------------------------------------
    step: int = Field(..., description="1-indexed iteration number")
    # 何回目のイテレーションか（1始まり）。
    input_tokens: int = Field(..., description="Tokens sent to the LLM for this step")
    # このステップでLLMに送った（システムプロンプト+会話履歴を含む）トークン数。
    output_tokens: int = Field(..., description="Tokens generated by the LLM for this step")
    # このステップでLLMが生成したトークン数。
    request_time_ms: float = Field(..., description="Wall-clock time for the LLM API call in milliseconds")
    # LLM APIコール1回にかかった壁時計時間（ミリ秒）。パフォーマンス分析用。
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO 8601 timestamp of when this step was recorded")
    # このステップが記録された時刻。default_factory なのでインスタンス生成時に
    # 都度 datetime.now() が評価される（クラス定義時に固定されるわけではない）。
    api_url: str = Field(default="", description="Base URL of the LLM API endpoint (e.g., 'https://openrouter.ai/api/v1')")
    # どのプロバイダのエンドポイントを叩いたか。
    model_name: str = Field(default="", description="Model identifier used for this step (e.g., 'qwen/qwen3-235b-a22b-2507')")
    # どのモデルを使ったか。
    llm_output: str = Field(default="", description="Raw text generated by the LLM before code extraction")
    # 【重要】コード抽出「前」のLLM生テキスト全文。Thought部分も含む無加工の応答そのもの。
    # orchestrator.py では gen.text がそのままここに入る（llm_output=gen.text）。
    sandbox_input: str = Field(default="", description="Python code sent to the sandbox for execution")
    # 【重要】上の llm_output から code_extraction.extract_code() が抜き出した
    # 「実際にサンドボックスへ送ったコード部分だけ」。llm_output と中身は別物。
    # 両方を残すのは、「LLMがThoughtを書いていたか」「コード抽出が正しく機能したか」
    # を後から個別に検証できるようにするため。
    sandbox_output: str = Field(default="", description="Sandbox execution result (stdout/stderr/error message)")
    # サンドボックスの実行結果（標準出力・標準エラー・エラーメッセージ文字列）。
    # 次のターンで LLM に見せる Observation の中身そのもの。
    retries: int = Field(default=0, description="Number of LLM API retries before getting a successful response (0 = first attempt succeeded)")
    # 成功するまでに何回リトライしたか（0なら1回目で成功）。llm/client.py 側の
    # キーローテーション・リトライ処理の結果がここに反映される。


class SolutionOutput(BaseModel):
    """Output from student solution - required format for evaluation.

    This is the JSON structure your agent must produce and write to solution.json.
    The moulinette validates this against task correctness and metrics limits.
    """
    # -------------------------------------------------------------------
    # 【日本語解説】SolutionOutput = タスク1つ分の最終成果物
    # -------------------------------------------------------------------
    # StepMetrics が「1ステップ」の記録なのに対し、こちらは「タスク全体のサマリ
    # + 全ステップの履歴」をまとめたもの。agent_mbpp.py / agent_swebench.py が
    # これを組み立てて solution.json に書き出し、moulinette がそれを読んで
    # 正誤判定・メトリクス上限チェックを行う。
    #
    # 注意: success: true は「エージェントが final_answer() を呼んだ」という
    # 意味でしかなく、「本当に正しい」ことの証明にはならない
    # （BENCHMARK_REPORT.md のアブレーション実験で、success: true なのに
    # 空文字列パッチだった事故が記録されている）。
    # -------------------------------------------------------------------
    task_id: str = Field(..., description="Task identifier (MBPP task_id as string, or SWE-bench instance_id)")
    # どのタスクを解いたか（MBPPなら数値IDの文字列、SWE-benchならinstance_id）。
    benchmark: str = Field(..., description="Benchmark type: 'mbpp' or 'swebench'")
    # "mbpp" か "swebench" のどちらか。
    success: bool = Field(..., description="Whether the agent believes it solved the task")
    # エージェント自身が「解けた」と申告したか（final_answer()が呼ばれたか）。
    solution: str = Field(..., description="For MBPP: the Python function code. For SWE-bench: the git patch (diff)")
    # 実際の解答本体。MBPP なら Python の関数コード、SWE-bench なら git diff 形式のパッチ。
    iterations: int = Field(..., description="Number of agent loop iterations used")
    # ループを何回まわしたか（= steps の要素数と一致するはず）。
    total_requests: int = Field(..., description="Total number of LLM API requests made (including retries)")
    # LLM APIコールの合計回数（リトライも含む）。
    total_input_tokens: int = Field(..., description="Sum of input_tokens across all steps")
    # 全ステップの input_tokens 合計。
    total_output_tokens: int = Field(..., description="Sum of output_tokens across all steps")
    # 全ステップの output_tokens 合計。
    # 補足: total_input_tokens/total_output_tokens は理屈上 steps を合計すれば導出
    # できる値だが、あえてトップレベルにも持たせているのは、moulinette が集計処理
    # をせずに一発で予算超過チェックできるようにするため（steps側は詳細な監査用、
    # トップレベル側は合計値チェック用、という役割分担）。
    total_time_seconds: float = Field(..., description="Wall-clock time from agent start to finish")
    # エージェント起動から終了までの実時間。
    steps: List[StepMetrics] = Field(default_factory=list, description="Per-step metrics - one entry per agent iteration")
    # 前述の StepMetrics のリスト。1エントリ = 1イテレーション。
    system_prompt: str = Field(default="", description="Full system prompt sent to the LLM (for provenance checking)")
    # 実際に送った完全なsystem prompt。「本当に規定のプロンプトを使ったか」を
    # 後から検証できるようにするための provenance（来歴）チェック用。
    error: Optional[str] = Field(default=None, description="Error message if the agent failed (None if successful)")
    # 失敗時のエラーメッセージ（成功時は None）。
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO 8601 timestamp of when the solution was produced")
    # このSolutionOutputが生成された時刻。


class SandboxConfig(BaseModel):
    """Configuration for the secure code execution sandbox.

    Uses an allowlist approach: only imports in authorized_imports are permitted.
    Everything else is blocked by default.
    """
    # -------------------------------------------------------------------
    # 【日本語解説】SandboxConfig = サンドボックスの「門番」設定
    # -------------------------------------------------------------------
    # 「エージェントのコードにどこまでの権限を与えるか」を数値とリストで固めた
    # 設定オブジェクト。実際に効かせているのは sandbox/executor.py 側で、ここは
    # あくまで設定値の入れ物にすぎない。
    #
    # agent_mbpp.py と agent_swebench.py では実際の値に明確な差がある:
    #   MBPP     : allowed_directories=[SCRATCH_DIRのみ], timeout=20s, memory=256MB
    #   SWE-bench: allowed_directories=["/testbed", SCRATCH_DIR], timeout=60s, memory=512MB
    # MBPPは短いアルゴリズム問題しか解かないのでリソースを絞り、SWE-benchは
    # Dockerでマウントされた実リポジトリを調査・修正する必要があるため広めに取る。
    # -------------------------------------------------------------------
    authorized_imports: List[str] = Field(default_factory=list, description="List of allowed import names (e.g., ['math', 'json', 're']). Glob patterns like 'math.*' are supported.")
    # importのホワイトリスト。ここに無い名前は import した瞬間にブロックされる
    # （デフォルト拒否方式）。"math.*" のようなglobパターンで、math モジュール配下の
    # サブモジュールをまとめて許可することもできる。
    allowed_directories: List[str] = Field(default_factory=list, description="List of filesystem paths the sandbox can access (e.g., ['/testbed', '/tmp/agent'])")
    # ファイルシステムアクセスを許可するパスのリスト。ここに含まれないパスへの
    # open() はすべて拒否される。
    max_execution_time_seconds: int = Field(default=30, description="Maximum wall-clock time for a single sandbox execution before timeout")
    # 1回のサンドボックス実行にかけられる壁時計タイムアウト（秒）。
    # 無限ループや暴走コードを殺すための上限。
    max_memory_mb: int = Field(default=512, description="Maximum memory in megabytes for sandbox execution")
    # サンドボックス実行に許可する最大メモリ（MB）。
    max_output_chars: int = Field(default=20_000, description="Maximum characters of sandbox stdout returned per execution before truncation (project-internal, not required by the moulinette)")
    # 標準出力が長すぎるとトークンを食い潰すので切り詰める上限文字数。
    # moulinette契約外、プロジェクト内部だけの都合で存在するフィールド。


class MBPPTaskInput(BaseModel):
    """Input for an MBPP task - provided by the moulinette.

    Your agent receives this as the task definition to solve.
    """
    # -------------------------------------------------------------------
    # 【日本語解説】MBPPTaskInput = moulinette からエージェントへの入力（MBPP版）
    # -------------------------------------------------------------------
    # SolutionOutput の逆方向。moulinette がエージェントに投げてくるMBPPタスクの
    # 定義そのもの。agent_mbpp.py が起動時にこの型でタスクJSONをパースする。
    # -------------------------------------------------------------------
    task_id: int = Field(..., description="MBPP task identifier (integer)")
    # MBPPタスクの識別子（整数）。
    task_definition: str = Field(..., description="Natural language description of the function to implement")
    # 自然言語の問題文。LLMへのuser messageに直接埋め込まれる。
    function_definition: str = Field(..., description="Function signature (e.g., 'def solve(nums):')")
    # 関数シグネチャ（例: "def solve(nums):"）。LLMがこの通りの名前・引数で
    # 書かないと公開テストが通らない。
    test_imports: List[str] = Field(default_factory=list, description="Import statements needed to run the public tests")
    # 公開テストの実行に必要なimport文。候補コード自身が必要とするとは限らない
    # （例: テストのassertion側だけがmath.iscloseを使うケース）。
    # mcp_tools_mbpp.py の _test_imports() がこれを候補コードの前に自動で前置する。
    test_list: List[str] = Field(default_factory=list, description="Public test assertions the solution must pass")
    # 公開テストのassert文そのもの。エージェントはこれをMCPツール run_tests
    # 経由で実行して自己検証する。


class SWEBenchTaskInput(BaseModel):
    """Input for a SWE-bench task - provided by the moulinette.

    Your agent receives this and must produce a git patch that fixes the issue.
    """
    # -------------------------------------------------------------------
    # 【日本語解説】SWEBenchTaskInput = moulinette からエージェントへの入力（SWE-bench版）
    # -------------------------------------------------------------------
    # 実世界のバグ修正に必要な情報一式。各フィールドは単なるデータではなく、
    # 後続コードの入力パラメータそのものになる。例えば agent_swebench.py では
    #   container = SweBenchContainer(task.docker_image)
    #   container.start(eval_script=task.eval_script, tools_file=TOOLS_FILE)
    # のように、docker_image はそのまま docker pull されるイメージ名、
    # eval_script はそのままコンテナ内で実行されるbashスクリプトになる。
    # -------------------------------------------------------------------
    instance_id: str = Field(..., description="SWE-bench instance identifier (e.g., 'sympy__sympy-23534')")
    # SWE-benchのインスタンス識別子（例: 'sympy__sympy-23534'）。
    problem_statement: str = Field(..., description="The GitHub issue description - what needs to be fixed")
    # 実際のGitHub issue文面。何を直すべきかの説明。
    docker_image: str = Field(..., description="Full Docker image name to pull (e.g., 'swebench/sweb.eval.x86_64.sympy_1776_sympy-23534:latest')")
    # そのバグを再現できる環境まるごとのDockerイメージ名。docker_runner.py が
    # これを docker pull する。
    eval_script: str = Field(..., description="Bash script to run inside the container to evaluate the patch")
    # パッチが正しいか判定するbashスクリプト。docker_runner.py がコンテナ内へ
    # 書き込み、mcp_tools_swebench.py の run_tests() がこれを実行する。
    hints_text: str = Field(default="", description="Optional hints about the issue (may be empty)")
    # 補助的なヒント情報（空でもよい）。
    repo: str = Field(default="", description="Repository name (e.g., 'sympy/sympy')")
    # リポジトリ名（例: 'sympy/sympy'）。
